// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBiRbpTuxBzYaU38g4Odim8K5xzMMdb90',
    appId: '1:849709741071:web:13132cff3016ccab771f7a',
    messagingSenderId: '849709741071',
    projectId: 'coptic-app-c115f',
    authDomain: 'coptic-app-c115f.firebaseapp.com',
    storageBucket: 'coptic-app-c115f.appspot.com',
    measurementId: 'G-91H21PF3CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBblW8phNUoGKeUYhbbp87H94d-Ux2I9nM',
    appId: '1:849709741071:android:c9d3ab12a34c56f1771f7a',
    messagingSenderId: '849709741071',
    projectId: 'coptic-app-c115f',
    storageBucket: 'coptic-app-c115f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQq7krIezE7Bra9gvj7mOO7V_vYTU4RjY',
    appId: '1:849709741071:ios:46739b9f719d88e4771f7a',
    messagingSenderId: '849709741071',
    projectId: 'coptic-app-c115f',
    storageBucket: 'coptic-app-c115f.appspot.com',
    iosBundleId: 'com.example.elkeraza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQq7krIezE7Bra9gvj7mOO7V_vYTU4RjY',
    appId: '1:849709741071:ios:46739b9f719d88e4771f7a',
    messagingSenderId: '849709741071',
    projectId: 'coptic-app-c115f',
    storageBucket: 'coptic-app-c115f.appspot.com',
    iosBundleId: 'com.example.elkeraza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBiRbpTuxBzYaU38g4Odim8K5xzMMdb90',
    appId: '1:849709741071:web:04333fe2f6d6ba94771f7a',
    messagingSenderId: '849709741071',
    projectId: 'coptic-app-c115f',
    authDomain: 'coptic-app-c115f.firebaseapp.com',
    storageBucket: 'coptic-app-c115f.appspot.com',
    measurementId: 'G-KLVHGVK38N',
  );
}
